version: "3.10"
services:
  worker:
    build: .
    environment:
      - YOUR_OPENAI_API_KEY=${YOUR_OPENAI_API_KEY}
      - YOUR_TELEGRAM_BOT_TOKEN=${YOUR_TELEGRAM_BOT_TOKEN}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
